/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { a } from '@react-spring/three';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Union_4001: THREE.Mesh
  }
  materials: {
    ['SVGMat.005']: THREE.MeshStandardMaterial
  }
}

export const Logo: React.FC<JSX.IntrinsicElements['mesh']> = React.forwardRef((props, ref) => {
    const { nodes } = useGLTF('/logo.gltf') as GLTFResult;

    return (
        <a.mesh geometry={nodes.Union_4001.geometry} scale={65} {...props}>
            <a.meshPhongMaterial shininess={5} color="#5A5A5A" />
        </a.mesh>
    )
})

useGLTF.preload('/logo.gltf');
